+----------------------------------------------------------------------------------------------------+
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooo=+::+=ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooo+~.~~~.+ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==ooooo|
|ooooooooooooooooooooooo=..+o==:.+oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo:~=oooo|
|ooooooooooooooooooooooo:.~=ooo=.:oooooooooooooooooooooooooo=:::+oooooooooooooooooooooooooooo=~:ooooo|
|ooooooooooooooooooooooo:.:oooo=.+ooooooooooooooooooooooooo+~:==~+ooooooooooooooooooooooooooo+.:ooooo|
|ooo=++ooooooooooooooooo:.:oooo:.=oooooooooooooooooooooooo=~~=oo=~ooooooooooooooooooooooooooo:.+ooooo|
|ooo:..=oooooooooooooooo:.:ooo=~:ooooooooooooooooooooooooo+.:ooo=~=ooooooooooooooooooooooooo=~.=ooooo|
|ooo===ooooooooooooooooo+.~ooo:.+ooooooooooooooooooooooooo:.=ooo=~=ooooooooooooooooooooooooo=.~=ooooo|
|ooooooooooooooooooooooo=..=o+.~=ooooooooooooooooooooooooo:.=ooo=:=ooooooooooooooooooooooooo=.:oooooo|
|ooooooo==ooooooooooooooo:.==~~=oooooooooooooooooooooooooo:.=ooo=~=ooooooooooooooooooooooooo:.+oooooo|
|ooooooo:~=oooooooooooooo+.+:.=ooooooooooooooooooooooooooo=.+ooo+~=ooooooooooooooooooooooooo:.=oooooo|
|ooooooo=.:=ooooooooooooo=...:+::==ooooooooooooo==:+=ooooo=.:oo=::ooooo===+==ooooooooooooooo~~=oooooo|
|oooooooo:.:ooooooooooooo=...~:+:~~:ooooooooo=+:~:::::ooooo:.=o+~=ooo=+::++:~=ooooooooooooo=~:ooooooo|
|oooooooo=~.+ooooooooooo=~..:=ooo=:.=oooooo=::+=.:oo=:+oooo=.:=~+ooo=:~=ooo=::oooooooooooooo==ooooooo|
|ooooooooo=~.=ooooooo==:~+:.=ooooo+.+ooooo=~:=oo:.+oo+:ooooo+..:oooo:~=ooooo+.=oooooooooooooooooooooo|
|oooooooooo=..=ooooo+:~+oo:.=ooooo+.:ooooo+.=ooo=+~:==:oooo=+..:===+.~=oooo=~.:ooooooooooo=+:=ooooooo|
|ooooooooooo+.~=ooo:~+=ooo=.+ooooo=~:ooooo+.:ooooo=:~~:++::::==:::~::.:===:~+=~:==o===oooo=~~+ooooooo|
|oooooooooooo+.:=oo=oooooo=.:oooooo:.+=oo=:~~:=ooo==~:=====ooooo=o==o=:::::=oo=+::::::ooooo==oooooooo|
|ooooooooooooo:.:ooooooooo=.~=oooooo+:::::+o=:~:::::=oooooooooooooooooo=ooooooooo=o=ooooooooooooooooo|
|ooooooooooooo=~.+ooooooooo:~=oooooooo===oooooo====oooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooo=:.+oooooooo=ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooo=+=oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
+----------------------------------------------------------------------------------------------------+
                                      +----------------------------------------------------------------------------------------------------+
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooo========oooooooooooooooo==+=====ooooooooooooo====++++=====ooooooooooooooooo|
|oooooooooooooooooooooo=++++====+==oooooooooooo=+:+======+++=ooooooo==============+====oooooooooooooo|
|oooooooooooooooooooo=++==oooooo=:+oooooooooooo++=oooooooo=++=ooooo=:+===ooooooooooo==++==ooooooooooo|
|oooooooooooooooooooo++=ooooooo=+:=ooo==oooooo=:+=ooooooooo++=oooo=~==oooooooooooooooo=+++=oooooooooo|
|oooooooooooooooooooo+=ooooo====.+=====+=======+:+oooo===+++==oo==:+ooooooooooooooooooo=+++=ooooooooo|
|oooooooooooooooooooo=++++++:+++~+=++++~+::+==++~==+++++++=oooooo++o==oo====ooo+=o=+=ooo=:++ooooooooo|
|oooooooooooooooooooooo========+:+:++=====+=++:~:=++====ooooooooo:+o=+=++=++==+++==+oooo=+:==oooooooo|
|oooooooooooooooooooooooooo===+:+=====o==ooooo====~++=oooooooooo=:=o=+=+==++===o====oooo=++=ooooooooo|
|ooooooooooooooooooooooooo=+:~+=======o=o=o==oooo==++++=ooooooooo+=oo=ooooooooooooooooo=+++=ooooooooo|
|oooooooooooooooooooooooo==+~+=o=+====oooooooooooooo=+:=o=ooooooo=+=oooooooooooooooooo=+++=oooooooooo|
|oooooooooooooooooooooooo===~+=====o===oooooooo===oo==:+=o=ooooooo=:+oooooooooooooooo=++==ooooooooooo|
|ooooooooooooooooooooooo==o+.+=========ooooooo===++=o=:+=o=oooooooo=.+o=oooooooooo==+++==oooooooooooo|
|ooooooooooooooooooooooo===+.+===o===oooooooooo=====oo+~==o=ooooooo=~=o=++++=++++++===ooooooooooooooo|
|oooooooooooooooooooooooo=o:~++=o+++~+ooooooo=++=+=o===~+=o==oooooo=~==::==========oooooooooooooooooo|
|ooooooooooooooooooooooo=o=~+==o=+:++=oooooooo+++:+o==o+~=o=ooooo==:~++=ooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooo==:+===o==o=oo=======oo=====oo==:+=oooo==+::+==oooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooo+:+==+==oooo=:+======:+oooo=o===+:==oooo===oooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooo=~=========o=+++++++::+=oo=o=====~+=ooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooo++++=oo==++==========ooo======+++ooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooo==+++===o====oooooooo======+++=oooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooooo==+++++===oo==o=======++++=oooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooo===++:~:=+++++++::++=ooooooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooooooooooooo=+:====+:++=ooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooo=+=ooo=:=ooo=oooo=oooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooooooooooo==+++++===++==ooo=oo=oooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooo==+:...:.++++=:.+==o=ooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooo==:~~:~.~::=o=:++:~:=+==oooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooo=~.~:~.:++:=oo++++:.~+=+=ooooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooooo=:++:~..~:+:==++::+++:++::ooooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooooo::==:..~.~+++++=:+++++~:+:+=ooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooo==oooooooo=+~++...~:+++++=oo::++++~.:+~=ooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooo=+~+~.:+++++++:=oo+~++++~..~~=ooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooo+:+.~:++++:++++oo+++===+++++oooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooo=+:..~~:::++++=ooooooooo=+==oooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooooo=+~:++====oooooooooooo=+=oooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooo=====+=ooooooo=o====+=oooo+=oooooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooooo==+:=oo===+:+::~+=oooo=+ooooooooooooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooooooooooooo=~+oo=:~+===o==+=oo=:+ooooooooooooo=oooo===oooooooooooooooooooooooooooo|
|oooooooooooo==============ooo=::=o++=oooooo=:+oo+:=oo=======================oooooooooooooooooooooooo|
|ooooooo==++++++++++=++++++++==+:+o+=ooooooo++=o=::==+=++====oooooooooooooo=====ooooooooooooooooooooo|
|ooooo==+++===oooooooooooo=====+::==+=ooooo=+=====+===oooooooooooooooooooooo==o=+==oooooooooooooooooo|
|oooo=====ooo=oooooooooooooooooo====++=ooooo=+====oooooooooooooooooooo=oooooo+oo=+===oooooooooooooooo|
|oooo=+++=oo=+oooooooooooooo===========ooo=oooo===+++++=====o=oo=o==o=+======+++++=oooooooooooooooooo|
|oooooo=+++==+==o=================oooooooooooooooo===================++==+++====ooooooooooooooooooooo|
|ooooooooo===+++++=======oooooooooooooooooooooooooooooooooooooooooooooooo=ooooooooooooooooooooooooooo|
|oooooooooooooooo=ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
+----------------------------------------------------------------------------------------------------+
                                      +----------------------------------------------------------------------------------------------------+
|oooooooooooooooooooo==oooooooooo==oooo=ooooooooooooo=ooooooooooooooooooooooo==+++====+=+++==oooooooo|
|oooooooooooooooooooo:~:=+:++++o=~~oo~+:+++++++=:=o+:~=++oo++=++++=+++=+=oo====oooooooooooo===+=ooooo|
|oooooooooooooooooooo::::~.:~.+=+.:==~::+.:~::~+~:=.:~~~~==~.:~+~+~~:~::oo+=oo=+=ooooo=====+====+=ooo|
|oooooooooooooooo========++=++===+====+++:=====:+=o======oo=============o++o=::~~~~+=o=++++=+==oo++oo|
|ooooooooooooo=+===++++=o==+==++==oooooo==+=ooo~+oooooooooooooooooooooooo+=+.~~~~~~.~==++++=+o==oo++o|
|ooooooooooo=++=o+......+=++=+=+++=ooooooo=+=oo:=oooooooooooooooooooooooo++..~~+:~.~.:==++++=++===+++|
|oooooooooo=+=oo=...++..~=====o===ooo====+=+ooo~=ooooooooooooooooooooooooo:.:+:==+::=o=++++===oooooo+|
|oooooooooo+=oooo++:+++:+oo==============oooooo~=ooooooooooooooooooooooooo==:++++===oo=++++=+===oooo+|
|oooooooooo:=o=o=o=+++==oo++==o=ooooooooooooooo.=ooooooooooooooooooooooooo=++ooooooooo=++=++=o======+|
|oooooooooo===============:oo=++++=oooooooooooo~=oooooooooooooooooo====oo=+==++++==ooo========+==o=oo|
|ooooooooooooooooooooooo=+:::~~~~~~~:+=+=======~=ooooooooooooooo=~......~:+++=ooo==========+==ooooooo|
|ooooooooooooooooooooooo==:~.~~~:::~~:=ooo=====~oooooooooooooo=~..........:ooooooooo=o=oooooooooooooo|
|oooooooooooooooooooooo++=~~.~::~~::~~:=oooooo=~=oooooooooooo=.............=oo=o=oooooooooooooooooooo|
|oooooooooooooooooooooo+++:~::==~~::~:~~=ooooo=~=oooooooooooo:.....:~.....~======++===ooooooooooooooo|
|oooooooooooooooooooooo:.:+:~::+~::~:::~~=oooo=~ooooooooooo++~.....ooo=:~::ooooooooo==+=ooooooooooooo|
|oooooooooooooooooooooo++:===+:~~.:::~::~~++==+~oooooooooo=+o=.....:==+::+=oooooooooooo+=oooooooooooo|
|oooooooooooooooooooooo:==++o=++++~::~:~::..:++~oooooooooo=+oo+:~..~~+~+=oooooooooooooo=+oooooooooooo|
|o===============oooooo+===++=====+.~:::::~::~~~ooooooooooo++=oo===++==+++=====ooo======:+o+=++=++=oo|
|o====o==========oooooo+=+==oo=o=++:~:~:::::::.~oooooooooooo:+=====:+o===++++++++++======+=+=ooo=oooo|
|oooooooooooooooooooooo:ooo=========:::~~:~~:~~~oooooooooooo++ooooo=++===+=+==oo==ooooooo=++========o|
|ooooooooooooooooooooo=+oooo+===oooooo=++:+++=+:oooooooooooo=+ooooooo==+=+:+++ooooooooooo=:++=+++++=o|
|ooooooooooooooooooooo++ooooo==o=+=+o====oo===+~oooooooooooo=+oooooooooooo===ooooooooooooo++====+++oo|
|ooooooooooooooooooooo+=oo====ooo===o===+oo=+=+:ooooooooooooo+=oooooooooooooooooooooooooo=+oooooooooo|
|ooooooooooooooooooooo+=oo=++=oooo====o=oooooo+:ooooooooooooo+ooooooooooooooooooooooooooo=+oooooooooo|
+----------------------------------------------------------------------------------------------------+
                                      +----------------------------------------------------------------------------------------------------+
|++++++++++++++++++++++++++++++++++++++++++=+++++++++++++++++++++++++++++++++++++++++++++++++++++++++|
|+=o==oooo==oo==o=oo==o=oo==o=oo==o=oo==o===oo=o==oo=o==oo==oo==o=o=oo=o==oo==oo==oo==o=o=oo=oo=oo=++|
|+=oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=+|
|+=oooooooooooooooooooooooooooooooooooooo++o======+===+=o=+=oo====o++o=+o=+========o++ooooooooooooo++|
|+=ooooooooooooooooooo=oooo=oooooooooooo.~.~.~..:..~.....~~.o+...~~~...~~~.~.~..:.~.~.~+ooooooooooo++|
|+=oooooooooooooooooo:.~o+~~~o=oooooooo:.~......:..~..~~..:~o......:~:.~.~......+.:.+~.=ooooooooooo++|
|+=oooooooooooooooooo+....~.+oooooooooo=++:+:++++==++++==:+o=++++=:+o+:=++++:++=++=:+==oooooooooooo++|
|++oooooooooo=+++++::+~..:~+=+++++++:++=ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo++|
|+=ooooooooo:+=oooo==~~+=ooooo==~~++::~~~:=oooooooooooooooooooooooooooooooooooooooooooooooooooooooo++|
|+=oooooooo:+oo===oo=:=oooooooooo=~+++++:..:========ooooooooooooooooooooooooooooooooooooooooooooooo++|
|++oooooooo~=oo+~+oo:+ooooo=.:oooo+~++:..+~.~+:+++==++++====ooooooooooooooooooooooooooooooooooooooo=+|
|+=oooooooo:~ooo==o=.+oooooo==oo=o:~++~..~:~.~~~~~~:++=++++++++===ooooooooooooooooooooooooooooooooo++|
|+=ooooooooo+~++==~.~.=oo==oooooo+~++++...~:.:===+:~..~:+===++=+++++===oooooooooooooooooooooooooooo++|
|++oooooooooo=++:..:.~::+======+:~+++++....~.+======~+:~.~:+===+++==+=+++==oooooooooooooooooooooooo++|
|+=oooooooooooo=.~:.~o=.~::::~::+++++++~.....~+=++=+~o===:...~+==++++=====+++==oooooooooooooooooooo++|
|++ooooooooooo=.~~.=oo=.~~:~:+++++::+::~...+=~.~+=+~+=..+oo=:~..~====+========++==ooooooooooooooooo++|
|++oooooooooo=.~~~=oooo+~......~..~~~.~....ooo+..~~+=+..~===oo+~...+=========oo==+++==ooooooooooooo=+|
|+=oooooooooo.~~~oooooooo+.~o++~~~~.~:++...ooo=....~+~...=====:=o+~..~+=========oo==+++=ooooooooooo++|
|+=ooooooooo~.~~ooooooooo+.~ooooooooooo=...ooo~..+:......=+==:~==oo=:...+======o==oooo=+++ooooooooo++|
|+=oooooooo:.~~oooooooooo+..ooooooooooo+...ooo...ooo+....==+:~+=====oo+...+===+=====oooo=+:+ooooooo++|
|+=ooooooo=..:ooooooooooo:.~ooooooooooo+..~oo+..+oooo......~:+++======o++~..+o=====+===oooo++=oo=oo++|
|+=ooooooo..:oooooooooooo:.:ooooooooooo:..+oo~..ooooo....:...:===++===+~=o=~..+=oo==+:======+:ooooo=+|
|++oooooo+.~ooooooooooooo:.+ooooooooooo...ooo..:ooooo...~oo+~..~+==++~~====o=:..+===o=+oo=====ooooo++|
|+=ooooo=..oooooooooooooo~.oooooooooooo..~oo=..=oooo=...+oooo=+....~~+=++====o=:.~==+=+=ooooooooooo++|
|++ooooo~.=oooooooooooooo~.ooooooooooo=..+oo+..ooooo=...=oooooooo+~..~:+====++==~:~+ooooooooooooooo++|
|+=ooooo.+ooooooooooooooo.~ooooooooooo=..ooo:.+ooooo+...oooooooooooo=:~.~~:+=+:~+=+~~=oooooooooooo=++|
|+=oooo+~oooooooooooooooo.+ooooooooooo:.+ooo:.=ooooo+..:ooooooooooooooo=+:~~..~+++==+~+oooooooooooo=+|
|+=oooo=oooooooooooooooo=.=ooooooooooo..oooo~.oooooo:..=ooooooooooooooooooo==+::~~::++~~ooooooooooo++|
|+=ooooooooooooooooooooo..~oooooooooo:.=oooo~~oooooo:.~oooooooooooooooooooooooooo==++:+~~oooooooooo++|
|+=oooooooooooooooooooo+....=ooooooo=...=ooo+.oooooo..ooooooooooooooooooooooooooooooooooooooooooooo=+|
|+=oooooooooooooooooooo~...+.+oooooo~....+ooo.:ooooo+.+oooo=+++:o=+++++o+++:+++==:+o+:=+:+:++++++::++|
|++oooooooooooooooooooo.:~.+=+ooooo=.~..+.+oo=.+ooooo+.~ooo+.~..=~....:=...~...=~.:=...~...~......~++|
|+=oooooooooooooooooooo.=+..ooooooo=+o..==+ooo~.=ooooo+..=o+:+::=~::~:=o~+:+=:==::=+~=:~:+::::~~::+=+|
|+=ooooooooooooooooooooooo~.=ooooooooo:.+ooooo=.~oooooo+..+ooooooooo=++=++++o=:++=+++++:~+=oooooooo++|
|++oooooooooooooooooooooooo+=ooooooooo=.~oooooo~.=oooooo:..+oooooooo~.+=.~.=+......~..:...=oooooooo++|
|+=oooooooooooooooooooooooooooooooooooo++oooooo+.~ooooooo...=ooooooo++o=::~o+~::~::+:++~::ooooooooo++|
|+=ooooooooooooooooooooooooooooooooooooooooooooo..=oooooo=...=o::++:++++:o+++++==:=++++=:++:=ooooo==+|
|++ooooooooooooooooooooooooooooooooooooooooooooo..:ooooooo+..:+...~.....~=.....=~~..~...~...=o=oooo++|
|++ooooooooooooooooooooooooooooooooooooooooooooo:..oooooooo...~+=~+~+:~:+o~::::o~+:::~+~+:+:::~+ooo++|
|+=ooooooooooooooooooooooooooooooooooooooooooooo+..oooooooo+..~oooooooooooooooooooooooooooooooooooo++|
|+=oooooooooooooooooooooooooooooooooooooo====+++:..ooooooooo...=ooooooooooooooooooooooooooooooooooo++|
|+=oooooooooooooooooooooooooooo=++:~~.............+ooooooooo+..:o=ooooooooooooooooooooooooooooooooo++|
|+=oooooooooooooooooooooooo=:.............~~~++=ooooooooooooo...ooooooooooooooooooooooooooooooooooo++|
|++oooooooooooooooooooooooo=~~:+++====ooooooooo=++++++:::~~~:..~ooooooooooooooooooooooooooooooooooo++|
|+=oooooooooooo+=ooooooooooooooooooooooooo:~.................:+oooooooooooooooooooooooooooooooooooo++|
|+++==+==+==+++~++=++oo++===+==++=++=++=o+...........~~:=++=====+=++==+==+==+=o=+==+=+===++=+==+=++++|
|+....~..~...~~...~.~o~.+....~......~..=:~++..:..:.~:..==.:...=~...~+.~o~....+=..:..~....::..~.~+.~++|
|+.+~.:~.~~..+..~.:.:o.~+~~....~+.~...:o~.~...~..~~....=~.:~.~o~.~.:..+o.~~.~o=~........~:...~.++~o++|
|++o=++=+====+++=+++==++++==+++==+=++=+==:++==+=+++++=+=+++=+==++++++++=+==++=++++=++=+=++===++=++=++|
+----------------------------------------------------------------------------------------------------+
                                      +----------------------------------------------------------------------------------------------------+
|~+=================+=++++++===++:~:+=============++++++++++++++++:~~++=++++++++++++++++++++++++++++~|
|:ooooooooooooooooo===ooooo===ooo:.=oooooooooooo===+==++++=+++=+==+.:oo=oo=+++++++=++=+++++++++==ooo:|
|+ooooooooooooooo======+++===++oo:.=ooooooooooo========+++++====++:.:=o===+++++++++++++++=++++++===o+|
|+oooooooooooo=ooo====o=====++=oo:~=oooo====ooo======+=+o++++++====~:o====+++++=+++++++++=+++++==+==~|
|+ooooooooooo====ooo===o+++==oooo:~=====++++=+=+++==++o==:=ooooooo=~:oo=====oo=o==========oooo===+:+:|
|+oo=o=========o+=oooo==:=ooooooo:.=o=+++=====+=+++:+=oo=:oooooooo=.:ooooo==+======o==o=oo+++++++=oo+|
|+ooo==oo=o====+:=oooo=:=oooooooo:~=oooo+++++~++++=+===++~==oooooo=~:oooooo===+====oo=o=oo==+=++==oo+|
|:oooo==+==++++===oooo===oooooooo:.=oooo====+:o=+==+====++=ooooooo=.:oo=oo=+++======+=======o++++:+=+|
|+ooo=ooo=:+o=oooooo=======oooooo:.=ooo==ooo++=============ooooooo=~:o=~+o+::=++++++++++++++++++=:~++|
|+ooooo=:...:=oo=ooo+======oooooo:~=oo=ooo=:...~=oooo==oo===oooooo=.:++====+:+:++===========++++::+=+|
|+oo=o=~.....+==ooo=++===+=oooooo:.=oooooo+...~~+o=oo=+=====oooooo=~:========+++++=o+:++=++=:++++ooo+|
|:oo===:++:+++==o===++==:+=oooooo:~=o=o==o+++++++oooo===+::+oooooo=.:oo==========++:..~+===o++==+ooo+|
|+o==+=+++:+=oo=o====+++=oooooooo:~=ooooo==+:+=====oooo++:+==ooooo=~:ooo===+====+++++++==ooo=+++=ooo+|
|:o=oo=+=+:+=oo=ooo=++++:=ooooooo:.=oo==oo=+:==ooooooo=+++:=oooooo=.:o=oo=+++=====o=+:+=ooooo+++=ooo+|
|:oooo==+~.++ooooooo=++++=ooooooo:.=ooooo=+:.++=oooooo=+++++oooooo=.:o===++++:====o+:~:=oooo=:+:=ooo+|
|~+====+....~=======+....+======+:~:=====+.....=======+....+======:~~+==++++++====+....~+===+~~:+==+:|
|::::~::~~~~:::::::::::~::::::~~:::~::~:::~~~~~::::::::~~~:~::::::~:::~:~:::~::~~~.~.~..~::::::+:::::|
|:~~:::+::+:+::+::++::::::::~::::::::::::::+::::::::::::::::::::~:::::::::~::::::::::::::::::+:::+++:|
|~+=============================+~~:==============++++++++++++++=+:~:+====+++++++++++++++++++++++=++~|
|+oooooooooooooooooo=====o==o==oo:.=oooooooooooo=oo=++=+++++=++=o=:.:o=====++++++++++++=++++++++===o:|
|+oooooooooooooooo=o==+=+====++oo:.=oooooooooo=o===+===+++++==+++++.:=o=++++++++:+++++++++++++++++=o+|
|+oooooooo=oo=o=oo=====o=+++++ooo:~=o=o=================o++=====oo=.:o=oo=++++=+===++=+++==+++=+=o=+.|
|+oooo=ooooooo===o=oo==o++=oooooo:.==oo=++=+++++++==++oo=:=ooooooo=~:ooo=====oooooo====oooooo===+++=+|
|+oo============:=oooo=+:oooooooo:.=o===+++===+++++++====:=ooooooo=.:oooooo===+++=+o==o=o=++:+++=ooo+|
|+ooo====oo===+++o=ooo=+=oooooooo:~=oooo=++++~+++===+===+:==oooooo=~:oooooo====++++=========++:+++=o+|
|:oooo=====:+++=ooooo====oooooooo:~=ooooo=oo++o=+==+==o=+==ooooooo=.:oo====++==+++:+++++++++++=o=::++|
|+oooo=oo=~+ooo=o=oo=======oooooo:.=oooo==oo+++======o====+ooooooo=~:o=:=o+::+o++++:++++++++:+=o+::++|
|+ooo=o=~...~=oooooo====o==oooooo:~=oo=ooo=~....=oooo==o=o==oooooo=.:++====++:::+++====+=+++++:::+=o+|
|+oo=o=~.....+=o=oo=++==++=oooooo:.=o==ooo:~:~:~+oooo=+=++==oooooo=~:=========++++==:~~+=++=:+=++ooo+|
|:oo===+++:++==o====++=+++ooooooo:.=oooo=o=+:++++=ooo===+::+oooooo=.:ooo=========++~...===oo++==+ooo+|
|+oo==++++~+=oooo====++++oooooooo:~=o=o=oo=+:+===o==ooo=:++==ooooo=.:ooo===++====+=++++=oooo=+++=ooo+|
|:o=oo=+=+:==o==oo==++++:=ooooooo:.=ooo=oo=+:+=oo=oooo=+++:=oooooo=.:oooo=++++====o=+:+=oooo=++:oooo+|
|:ooooo=+~.++=oooooo=+++:=ooooooo:~=ooooo=::.+:=o=oooo=:++:+oooooo=.:oo==+++++===oo+~.~+oooo=:+:=ooo+|
|~++++=:....~+=++=+=+....+======+~~:++++++.....+=+==+++....:=====+::~:++++++++++=+~.....+=+++~.:++=+~|
|::~:~:~~~~~~:::~:~:~~~~::~~::::~:::::~:::~::::::::::::::::::::::~:::::~::~~::~:~~~~~~~~~:~~:::~:::::|
+----------------------------------------------------------------------------------------------------+
                                      +----------------------------------------------------------------------------------------------------+
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooo=o==========+=+++++ooooooooooooooooooooooooooo|
|oooooooooooooo=oo==============++++++++++::::::::~~~~~~~~~~~~~~~.~~~.~.~~=oooooooooooooooooooooooooo|
|ooooooo=~:::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+oooooooooooooooooooooooooo|
|ooooooo=..~~::::::::~::~~::~:~~:~:~::~~:~:~:~:~~~~~~:~~~~~:~~~~~~~~~~~~:~+oooooooooooooooooooooooooo|
|oooooooo~~:::::::::::::::::::::::::~~::~~~:~:~~::~::~~:~:::++====+:~~:~~~:oooooooooooooooooooooooooo|
|oooooooo:.:::::::::::::::::::~:~~::::::++++++::::::~::::~:=ooooooo+~:~~:::oooooooooooooooooooooooooo|
|oooooooo+~:+:+::+:+:+::++:::+++++++:::+=oooo+:::::::::::::=ooooooo=::+++===ooooooooooooooooooooooooo|
|oooooooo+:++++++++++++++++=ooooooooo=+:=oooo=::::::+:::::+ooooooooo+:~::~~+ooooooooooooooooooooooooo|
|oooooooo=:+++++++++=ooo=:=oooooooooooo++oooo=::::+:::::::=ooooooooo=+~:::::ooooooooooooooooooooooooo|
|oooooooo=+:+===:++:=oooo+=ooooo+++=ooo=+oooo=:+++++++++++=ooo=+ooooo=+:::::=oooooooooooooooooooooooo|
|ooooooooo+:+oo=:++:=oooo+=ooooo+::=ooo=+oooo=:+++++++++:+oooo+:+ooooo=+:+::=oooooooooooooooooooooooo|
|ooooooooo=:+ooo====ooooo+=ooooo+::+oooo+=ooo=:++++++++++=ooo====oooooo=+:+:+oooooooooooooooooooooooo|
|ooooooooo=:+=ooooooooooo++ooooo=+++oooo==ooo=:++++++++:=ooooooooooooooo=+:++=ooooooooooooooooooooooo|
|ooooooooo=::=ooo==+=oooo=+ooooo=:++oooo==oooo==o=ooo=:+oooo=++++++oooooo=+:+=ooooooooooooooooooooooo|
|ooooooooo=::=oo=+:+:=ooo=+oooooo+++=ooo=+============+=oooo+::++++=oooooo=+:=ooooooooooooooooooooooo|
|oooooooooo+:+ooo++=++oooo+=oooooo==oooo=:++:+++++:++:+ooooo+++++++:=oooooo=:+ooooooooooooooooooooooo|
|oooooooooo+~+ooo=:=++oooo+:+=ooooooo==++++====+=====+++++++:++==+=++=======:+ooooooooooooooooooooooo|
|oooooooooo+:++++++==++++++++++++++++++++=====+=====+==++++++=======+++++++++:ooooooooooooooooooooooo|
|oooooooooo=:=++++======++=====++++++=============+==========================+=oooooooooooooooooooooo|
|oooooooooo=:+++========================================================++++++=oooooooooooooooooooooo|
|ooooooooooo:+++++===============o==========oo=================================oooooooooooooooooooooo|
|ooooooooooo:++++++++======================:.:=+============o==oooooooooo===ooooooooooooooooooooooooo|
|ooooooooooo+:+++++++++==+==========oo=oooo~..ooooooooooooooooooooo===+++++++++oooooooooooooooooooooo|
|oooooooooooo=oo=oooooooooooooooooooooooooo+..=oooooooooooooo====++++++++++++::++++==oooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooo=..+ooooooooooooo==++++++==ooooo=+~~+++++++ooooooooooooooo|
|ooooooooooooooooooooooooooooooooooooooooooo..~ooooooooooo=++++++=ooooooooo=+~+o==+++:+oooooooooooooo|
|ooooooooooooooooooooooooooooooooooooooooooo~.~ooooooooo===++:+=oooooooooo=+~:oooo=+:+:+==ooooooooooo|
|ooooooooooooooooooooooooooooooooooooooooooo+..=ooooo===++++==ooooooooooo==:+ooooo==+:+:+==oooooooooo|
|oooooooooooooooooooooooooooooooooooooooooo==..=ooo==+++++++=oooooooo=~~+=+:oo=ooo===+:::+==ooooooooo|
|oooooooooooooooooooooooooooooooooooooooo=++++:+====++++++=+=oooooooo+...+:=ooooooo==+:::++=ooooooooo|
|ooooooooooooooooooooooooooooooooooooooo=+++:::++++++++++:=++=oooooooo==+:=o...=o=o==+:::+==ooooooooo|
|oooooooooooooooooooooooooooooooooooooo=++++::~~:++++=+++:~+=+++=======++=oo..~=oo===+:~:++=ooooooooo|
|oooooooooooooooooooooooooooooooooooooo=++:+::~~~~++++++++:~~::+++++++::~=oooooooo===+:::++=ooooooooo|
|ooooooooooooooooooooooooooooooooooooo=+++++::~~~~+++++++++::~~.~~:~::~:++====o====++~::++=oooooooooo|
|oooooooooooooooooooooooooooooooooooo=+++++:::+~:++++++++:+::~::~:~:::~.~++++++++++:::::+++=ooooooooo|
|oooooooooooooooooooooooooooooooooooo=+++:::++::+++++++++++::+:::~~::+:+~~.~:++++++:+~:++++==oooooooo|
|ooooooooooooooooooooooooooooooooooooo=+++:+::::+++++++++++++:+:::~~~~~~::~.~.~~:~:~~:++++++=oooooooo|
|ooooooooooooooooooooooooooooooooooooooo===++++~:+++++++++++++:::::~:~~~:~::~~~:~::++++++++=ooooooooo|
|ooooooooooooooooooooooooooooooooooooooooooooo=..+=+++++++++::::::::::~~~~~~~~::+++++++++++=ooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooo..~=+++++++++:++::::~~~~~~:~::::++++++++++++=ooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooo~.~++++++++++++:+:::::::~~~::::+++++++++++++=ooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooo+..=++++++++++++++++:::::::~:::++++++++++++=oooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooo=..===++++++++++++++:++::::::++++++++++++++=oooooooooo|
|ooooooooooooooooooooooooooooooooooooooooooooooo..+oo==+++++++++++++:++++++++++++++++++++=ooooooooooo|
|ooooooooooooooooooooooooooooooooooooooooooooooo~.:oooo==+++++++++++++++++++++++++::++++=oooooooooooo|
|ooooooooooooooooooooooooooooooooooooooooooooooo+..oooooo==+++++++++++++++++++++++++++=oooooooooooooo|
|ooooooooooooooooooooooooooooooooooooooooooooooo=..oooooooo===++++++++++++++++++:+++==ooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooo~.=oooooooooo=+=ooooo=====+:++====oooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooo======+:+==oooo==+~::+++++=ooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooo=+:+++++++:=o=o+++=+++++++=ooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
+----------------------------------------------------------------------------------------------------+
                                      +----------------------------------------------------------------------------------------------------+
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooo=ooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooo==::===ooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooo=++++=ooooooooooooooooooooooooooooo==+:~+==oooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooo=:::::::::+==oooo====ooooooooooooooo===o=:.~=oooooooooooooooooooooooooooooooooooooo|
|oooo+::+ooooooooo=::::=+:::::::=ooo=::=oooooooooooooo===ooo+~~:=oooooooooooooooooooooooooooooooooooo|
|oooo=:::oooooo==+=+::::::::::+::::=oo===ooooooooooooo==ooooo=+~.:+=ooooooooooooooooooooooooooooooooo|
|ooooo:::=ooooo+:::o::::::::+=oo=+:::=oo===ooooooooooo===oooooo=~..:=oooooooooooooooooooooooooooooooo|
|ooooo+::+oooooo:::=o:::+oooooooooo=+::=oo==ooooooooo=====+::~~::~~.:+ooooooooooooooooooooooooooooooo|
|ooooo=:::=ooooo+:::oo+:::=oooooooooo=++=ooo===ooooooo===========o=:...+ooooooooooooooooooooooooooooo|
|oooooo:::=oooooo:::+oo=:::+ooooooooooo====oooo=oooooo==oooooooooooo=:..~+ooooooooooo=:::::::::==oooo|
|oooooo=:::oooooo=:::=ooo=:::+=ooooooooo==oooooo===oooooooooooo::+oooo=:..~=ooooooooo=::+=:..:ooooooo|
|ooooooo::::======:::+ooooo=::::=ooooooooo==oooooo==ooooooooo:~.~:oooooo=:..~=ooooooooooooo=~.:oooooo|
|ooooooo=:::::::::::::=ooooooo+::::+=ooooooo==ooooo===oooo==~.~+=ooooooooo=~..~=ooooooooooooo:.~ooooo|
|oooooooo:::+oooooo::::ooooooooo=+::::==oooo==ooooooo=====+::=oooooooooooooo+~~~=oooooooooooo=..:oooo|
|oooooooo+~::=oooooo:::+oooooooooooo=+::+==o==ooooooooo=====oooooooooooooooooooooooooooooooooo:.~oooo|
|ooooooooo:::+oooooo=:::=ooooooooooooooo=o=oooooooooooooo=oooooooooooooooooooooooooooooooooooo:.~=ooo|
|ooooooooo:~::=oooooo:::+ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo:..=ooo|
|ooooooooo=::+=oooooo=:::oooo====+++=ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo~.~=ooo|
|ooooooooooooooooooooooo==+:::::::===oooooooooooooooooooooooooooooooooooooooooooooooooooooooo:..:oooo|
|ooooooooooooooooooooooo++++==::::=ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=..~ooooo|
|oooooooooooooooooooooooooooooo+:::+ooooooooooooooooooooooooooooooooooooooooooooooooooooooo=..~=ooooo|
|ooooooooooooooooooooooooooooooo=+:::+oooooooooooooooooooooooooooooooooooooooooooooooooooo+..+ooooooo|
|ooooooooooooooooooooooooooooooooo=::::+=ooooooooooooooooooooooooooooooooooooooooooooooo=:..+oooooooo|
|ooooooooooooooooooooooooooooooooooo=+::::=ooooooooooooooooooooooooooooooooooooooooooo+~..:=ooooooooo|
|oooooooooooooooooooooooooooooooooooooo=+::+==ooooooooooooooooooooooooooooooooooooo=:..~:=ooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooo==o===o=ooooooooooooooooooooooooooo==+::~::=oooooooooooooo|
|ooooooooooooooooooooooooooooooooooooooooooooooooooo=o=oo=oooo=o==o========+:::::+==ooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooo=o=o==:+:::::++:++===ooooooooooooooooooooooo|
+----------------------------------------------------------------------------------------------------+
                                      +----------------------------------------------------------------------------------------------------+
|~   ~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
|  ++++:. .~~~~~~~~~~~~~~. ~=~~=+=:~~~..~~~~~~~~~~~~~~~~~~~~.~~~~~~  .....  ~~~~~~~~~~~~~~~~~~~~~~~~~|
| .=oo=+~ .~.~.~~~~~~~ .~++===o=ooo====+:~.~~~~.~ ~  ~ ...... ~..~:+======++~. ~~~~~~~~~~~~~~~~~~~~~~|
| .=oo=+...~.~....~~~.++=====o=o=o=oo====o=+....::++++====o=.  :=oooooooooooo+. ~~~~ ~ ~   ..  .    ~|
|  =ooooooooooo=+~..+=ooo==oo=ooo========ooo=+.:oooooooooo=~  +oooooo=+++=ooo=+. ..~~~:+~ ~======+~ ~|
|  =ooooooooooooo=:=ooooo==oooooo========ooooo+~=oooooooo=+  +o===o==:.. :=oo=+. +ooooo=..+oooo=+~   |
|  +oooooooooooo=:=oooooo=ooooooo==+:+===oo=oo=+:=oooooooo+  ~.~~~++:~    =oo=+. +oooo=: .=ooo=+~  ~~|
|  =oooooooooooo++ooooooo=+.~+ooo=+.~~+==o======::ooooooo=+~  ~    .~:.~:+ooo=+..+oooo+~ ~oooo=:. ~~~|
|  +ooo===oooooo~=ooo=o=o=   :ooo===~.=o=======++.=oooooo=+~  ..~:+==ooooooo=+:  +ooo=+. +ooo=+.  ~~~|
|  +o=+:~~+==oo=~=========+:+=o=======o=====+++++~+oooooo=+  .+=oooooooo=ooo=+.  +ooo=:..=ooo+~..~~~~|
|  +o+~    :oooo~===================o=====+++++++.+oooooo=. +oooooo==+:~+=oo=+.  +ooo=~ ~oo=+:.  ~~~~|
|  +o+~ ~~  =ooo:+=++++++==============+~.:==+++~.+oooooo+ ~ooooooo=:    =oo+~   +o==+. .+::~.  ~~~~~|
|. +o+~. ~  +ooo=~++++++:::++=+==+++:.. .+=++++: ~=oooooo+ .=oooooo==~..+oo=+.   .:~.~.        ~~~~~~|
|  ++:.  ~~ :=+++~~+++++++~.....       ~+++++:~  +ooooooo=~..::+++++++++=o=+~  ~       .:++:. ~~~~~~~|
|~  .    ~. .... ~~~:+++++++~.. .    .:+++:~~..  +oooo===+:.   .        ~::~.  ~ .:++ .=ooo=+  ~~~~~~|
|~~~~~~~~~~~~ ~~~~~~~~~~::::++:~~~~~:::~~~~...:~ :++::~~~~.  .~~~~~~~~~~ .... ~ .ooo=. :++:..  ~~~~~~|
|~~~~~~~~~~~~~~~~~~~ .++~:~~~~~~~~~~~~~~~.~~=+=. ..        ~ ~~~~~~~~~~~~~~ ~~~  ~++~.       ~~~~~~~~|
|~~~~~~~~~~~~~~~~~~~~~~~=++~.~.........~~~::~.~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~       ~~~~~~~~~~~~~~|
|~~~~~~~~~~~~~~~~~~~~~~~~..==:::~:~=:::+~.~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
+----------------------------------------------------------------------------------------------------+
                                      +----------------------------------------------------------------------------------------------------+
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::.~.~~~..:~:::~.:~~:...:~:~~~::~~~:~.~:~~:~~:~~.~~~~.~:::::::::::::::::::::::::::::::::::::::::|
|::::~:.~........:~~~...~:..............:~...............~~::::::::::::::::::::::::::::::::::::::::::|
|::::::::::~:::~~:~.:::~:::::~~::::::::~:::~:~::~:~.~::~:::::::::::::::::::::::::::::::::::::::::::::|
|::::::~:::::::::::::::::::::::::~:~~::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::....~.:::~:..~..~.:~.~~~~..~~.::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::~~.~..~~~.:....~.~:~..~..~.:~:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|:::::::::::::::~~~:::::::::~::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::...:~::~::::::~::.~::~:~::~:~::~~:~:~.:~::~~:~::~~::::~::.~::::~:~~:~::::~::~:~::~::::::::::::|
|::::~:..~............~:........~...~:.~...~....:....:~.......~:.....~.~.~..~::.....~..~..:::::::::::|
|::::::~::~~~:~~.~~~:~::~~~~:~:~~~:~~:~:~~:~~:~~:~:~~::~.:~~~~::~~:~~~~~~~~~~~:~:~~~:~:~~~:::::::::::|
|:::::::::::::::~::::::::::::::::::::::~:::::::::::::::~~:::::::::::::::::::::::~::::::::::::::::::::|
|:::::::~~.~:.~~.:~.~.~:...~.~.~~~~.~~:~..~~..~~~~~~~.~..~.~~~~~~~~~.~~~~.:~~~:..::::::::::::::::::::|
|::::~:.~:.~:.~..~:...~:.~....~..~..~.::.~...~......~~..~..~..........~.~...~.~~:::::::::::::::::::::|
|::::::~~:::::::::::::::::::::::::::::::::::::::::::::::::::::~~:::::::::::::::::::::::::::::::::::::|
|::::::~~~:::::::::::::::::::::::~:~.::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::~:......:::~:.......:...~~...~~.::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::~:.~~~~~~.~..~~~~~:~~.~.~~.:~:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|:::::::::::::::~:~:::::::::~::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::...~~:~~~:~:~:~::.~:~::~~~~~::~~:~~~~:~~~::~~~.:~~~~::~~~:.~~~:~~~~~.~:~~~::::::::::::::::::::|
|::::~:.~~............~:......~..~..:....~...~........~..~.:..~...~.........~..~.::~~::::::::::::::::|
|::::::::::~:::~.:~::~:::::~::~~:::~:.~:~:~::..:~~::::~~::~::~:~:~::~~.::::~:~~~:~:::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::~:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::~:+========+:~::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::~:==+:::::::::==:~::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|:::::::::~+o:::+::::::::::==~::~:~::~:~::~:.:~::::::::::::~:::::::::::~::~::::::::::::::::::::::::::|
|::::::::~:o:~:=oo::::~::::~==~:.==~~:o+~~==.o:~::~:::::::~+=~~:~:::::~:oo~~::~:::~::~~::~:::::::::::|
|::::::::~o:~:~:oo~~~:~~~~~~:o~::~o~.o:o.~o~.o=~:=:.::~:=~~=o:.==~::~~:o~:o~~:o:::=~.o+::=:~:::::::::|
|::::::::~o+~~~~:==:~~::::~~:o~~:~====.=+==.~o:.~==.::.~o:.+o.~:::::.~o=~:o=.~o~~~+=~o~~.:o.:::::::::|
|::::::::~:o:~::~:+===ooo:~:=+.:::~oo.~~oo.~~o:~~==.o+~:o:.:o:~::::o~==.::~o:~o:::=:~o+::=:.:::::::::|
|:::::::::~==::::::::::+:::o+.:::::~~~::~~~:~~~::~~~~~:~~~~~:~.::~:.~~~~:::~~:o~~:~.~o~~:..::::::::::|
|:::::::::~o=++++::::::++==~.::::::::::::::::::::::::::::::::::::::::::::::::~:.::::~:.::::::::::::::|
|::::::::~==+:::+======+:~.~:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::~~.~~::~~~~~~~~~::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::~::::::::::::::::::|
|::::::::::::::::::::::::::::::::::::::::::::::::::~~~~~~~~.~.~~~~:~~~~~~~.~~~~~:.............~.....:|
|::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|
+----------------------------------------------------------------------------------------------------+
                                      +----------------------------------------------------------------------------------------------------+
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooo=ooooooooooooooooooooooooooooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooo==::===ooooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooooo=++++=ooooooooooooooooooooooooooooo==+:~+==oooooooooooooooooooooooooooooooooooooo|
|ooooooooooooooooo=:::::::::+==oooo====ooooooooooooooo===o=:.~=oooooooooooooooooooooooooooooooooooooo|
|oooo+::+ooooooooo=::::=+:::::::=ooo=::=oooooooooooooo===ooo+~~:=oooooooooooooooooooooooooooooooooooo|
|oooo=:::oooooo==+=+::::::::::+::::=oo===ooooooooooooo==ooooo=+~.:+=ooooooooooooooooooooooooooooooooo|
|ooooo:::=ooooo+:::o::::::::+=oo=+:::=oo===ooooooooooo===oooooo=~..:=oooooooooooooooooooooooooooooooo|
|ooooo+::+oooooo:::=o:::+oooooooooo=+::=oo==ooooooooo=====+::~~::~~.:+ooooooooooooooooooooooooooooooo|
|ooooo=:::=ooooo+:::oo+:::=oooooooooo=++=ooo===ooooooo===========o=:...+ooooooooooooooooooooooooooooo|
|oooooo:::=oooooo:::+oo=:::+ooooooooooo====oooo=oooooo==oooooooooooo=:..~+ooooooooooo=:::::::::==oooo|
|oooooo=:::oooooo=:::=ooo=:::+=ooooooooo==oooooo===oooooooooooo::+oooo=:..~=ooooooooo=::+=:..:ooooooo|
|ooooooo::::======:::+ooooo=::::=ooooooooo==oooooo==ooooooooo:~.~:oooooo=:..~=ooooooooooooo=~.:oooooo|
|ooooooo=:::::::::::::=ooooooo+::::+=ooooooo==ooooo===oooo==~.~+=ooooooooo=~..~=ooooooooooooo:.~ooooo|
|oooooooo:::+oooooo::::ooooooooo=+::::==oooo==ooooooo=====+::=oooooooooooooo+~~~=oooooooooooo=..:oooo|
|oooooooo+~::=oooooo:::+oooooooooooo=+::+==o==ooooooooo=====oooooooooooooooooooooooooooooooooo:.~oooo|
|ooooooooo:::+oooooo=:::=ooooooooooooooo=o=oooooooooooooo=oooooooooooooooooooooooooooooooooooo:.~=ooo|
|ooooooooo:~::=oooooo:::+ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo:..=ooo|
|ooooooooo=::+=oooooo=:::oooo====+++=ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo~.~=ooo|
|ooooooooooooooooooooooo==+:::::::===oooooooooooooooooooooooooooooooooooooooooooooooooooooooo:..:oooo|
|ooooooooooooooooooooooo++++==::::=ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=..~ooooo|
|oooooooooooooooooooooooooooooo+:::+ooooooooooooooooooooooooooooooooooooooooooooooooooooooo=..~=ooooo|
|ooooooooooooooooooooooooooooooo=+:::+oooooooooooooooooooooooooooooooooooooooooooooooooooo+..+ooooooo|
|ooooooooooooooooooooooooooooooooo=::::+=ooooooooooooooooooooooooooooooooooooooooooooooo=:..+oooooooo|
|ooooooooooooooooooooooooooooooooooo=+::::=ooooooooooooooooooooooooooooooooooooooooooo+~..:=ooooooooo|
|oooooooooooooooooooooooooooooooooooooo=+::+==ooooooooooooooooooooooooooooooooooooo=:..~:=ooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooo==o===o=ooooooooooooooooooooooooooo==+::~::=oooooooooooooo|
|ooooooooooooooooooooooooooooooooooooooooooooooooooo=o=oo=oooo=o==o========+:::::+==ooooooooooooooooo|
|oooooooooooooooooooooooooooooooooooooooooooooooooooooooo=o=o==:+:::::++:++===ooooooooooooooooooooooo|
+----------------------------------------------------------------------------------------------------+
                                      